load("C:\\Users\\lucas\\Documents\\NOVA SBE\\PhD\\Methodology\\Applied Methods for Digital Economy Research\\Prep 1 Lab Basics\\ceosal2.RData")
dt.ceo.salaries <- data.table(data)
library(data.table)
library(ggplot2)
library(stargazer)
rm(data)
coin.flip <- rbinom(n=10,size=1,prob=0.5)
X <- sum(coin.flip)
x <- rbinom(n=1000,size=10,prob=0.5)
qplot(factor(x),geom="histogram")
qplot(factor(x),geom="bar")
